### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fishace012** [Mixinors/Astromine#432]
I've built the mod from 1.20.1 dev branch but failed when i started the game

Uncaught exception in thread "main"
java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
    at java.base/java.lang.reflect.Method.invoke(Method.java:580)
    at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
    at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod astromine
    at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:480)
    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    ... 3 more
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
    at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
    at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
    at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:478)
    ... 7 more

**Comment by vini2003** [comment]
This issue has now been addressed in the NeoForge 1.21.1 port. Older versions are no longer supported.
